AllCops:
  TargetRubyVersion: 2.5

Metrics:
  Enabled: false

# Eval command can only be run as bot owner, so its 'safe' as long as you dont give random people owner.
Security/Eval:
  Exclude:
    - src/modules/commands/owner/eval.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - src/modules/patch_bot.rb

# The error is from the existing discordrb code and not from my monkey patch.
Style/ConditionalAssignment:
  Exclude:
    - src/modules/patch_await.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SymbolArray:
  EnforcedStyle: brackets
