source 'https://rubygems.org'
gem 'discordrb', git: 'https://github.com/meew0/discordrb.git'
gem 'rmagick'
gem 'ruby-opencv', :require => 'opencv'
gem 'faker'
gem 'mediawiki-butt'
gem 'nokogiri'
gem 'yt'
gem 'streamio-ffmpeg'
gem 'filesize'