source 'https://rubygems.org'
gem 'badass', git: 'https://github.com/charagarlnad/badass.git'
gem 'digest'
gem 'discordrb', git: 'https://github.com/meew0/discordrb.git'
gem 'faker'
gem 'filesize'
gem 'mediawiki-butt'
gem 'nokogiri'
gem 'rmagick'
gem 'ruby-opencv'
